title: DataRepublican
description: Tracking where the money goes
baseurl: ""
url: "https://datarepublican.com"
destination: docs

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/default.png

social: 
  name: DataRepublican

development:
  url: "http://localhost:4000"
  server_options:
    headers:
      Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0
    
production:
  url: "https://datarepublican.com"
  
include:
  - florida

favicon: /assets/images/favicon.png

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from